on: [push, pull_request]
name: CI

permissions:
    contents: read

env:
    BUILD_TIME:

jobs:
    build-windows:
        name: Build (Windows)
        runs-on: windows-latest
        defaults:
            run:
                shell: msys2 {0}

        steps:
            - name: Install dependencies
              uses: msys2/setup-msys2@v2
              with:
                  install: >-
                      git
                      base-devel
                      mingw-w64-x86_64-gcc
                      mingw-w64-x86_64-cmake
                      mingw-w64-x86_64-curl
                      mingw-w64-x86_64-SDL2
                      mingw-w64-x86_64-SDL2_image
                      mingw-w64-x86_64-SDL2_mixer
                      mingw-w64-x86_64-SDL2_ttf
                  update: true

            - name: Checkout
              uses: actions/checkout@v4

            - name: Configure CMake
              run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

            - name: Build
              run: ninja -C build

            - name: Prepare artifact
              run: |
                  cd build
                  find . -not -path './res/*' -not -path ./res -not -name UnitedTiles.exe -delete
                  echo "BUILD_TIME=$(date '+%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: UnitedTiles-Windows_${{env.BUILD_TIME}}
                  path: build/

    build-android:
        name: Build (Android)
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: 21
                  distribution: oracle

            - name: Build with Gradle
              run: |
                  . ./build_android.sh
                  echo "BUILD_TIME=$(date '+%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: UnitedTiles-Android_${{env.BUILD_TIME}}
                  path: build/
