on: [push, pull_request]
name: Continuous Integration

permissions:
    contents: read

jobs:
    build-windows:
        name: Build (Windows)
        runs-on: windows-latest
        timeout-minutes: 60

        steps:
            - name: Setup MSBuild
              uses: microsoft/setup-msbuild@v2

            - name: Install dependencies
              run: |
                  git clone https://github.com/microsoft/vcpkg.git
                  cd vcpkg
                  bootstrap-vcpkg.bat
                  vcpkg.exe integrate install
                  vcpkg.exe install curl sdl2 sdl2-image sdl2-ttf sdl2-mixer

            - name: Checkout
              uses: actions/checkout@v4

            - name: Configure CMake
              run: >
                cmake -S . -B build -G "Visual Studio 17 2022"
                -DCMAKE_BUILD_TYPE=Release
                -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

            - name: Build
              run: cmake --build build --config Release

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build-windows
                  path: build/
